---
assembly: hg19
build_author: alexkotlar
build_date: 2023-07-03T15:42:00
chromosomes:
- chr1
- chr2
- chr3
- chr4
- chr5
- chr6
- chr7
- chr8
- chr9
- chr10
- chr11
- chr12
- chr13
- chr14
- chr15
- chr16
- chr17
- chr18
- chr19
- chr20
- chr21
- chr22
- chrM
- chrX
- chrY
database_dir: '~'
fileProcessors:
  snp:
    args: --emptyField ! --minGq .95
    program: bystro-snp
  vcf:
    args: --emptyField ! --sample %sampleList% --keepPos --keepId
    program: bystro-vcf
files_dir: '~'
statistics:
  dbSNPnameField: dbSNP.name
  exonicAlleleFunctionField: refSeq.exonicAlleleFunction
  outputExtensions:
    json: .statistics.json
    qc: .statistics.qc.tsv
    tab: .statistics.tsv
  programPath: bystro-stats
  refTrackField: ref
  siteTypeField: refSeq.siteType
temp_dir: '~'
tracks:
  outputOrder:
  - ref
  - refSeq
  - phastCons
  - phyloP
  - gnomad.exomes
  - clinvar
  tracks:
  - build_author: alexkotlar
    build_date: 2023-07-03T15:42:00
    local_files:
    - chr1.fa.gz
    - chr2.fa.gz
    - chr3.fa.gz
    - chr4.fa.gz
    - chr5.fa.gz
    - chr6.fa.gz
    - chr7.fa.gz
    - chr8.fa.gz
    - chr9.fa.gz
    - chr10.fa.gz
    - chr11.fa.gz
    - chr12.fa.gz
    - chr13.fa.gz
    - chr14.fa.gz
    - chr15.fa.gz
    - chr16.fa.gz
    - chr17.fa.gz
    - chr18.fa.gz
    - chr19.fa.gz
    - chr20.fa.gz
    - chr21.fa.gz
    - chr22.fa.gz
    - chrM.fa.gz
    - chrX.fa.gz
    - chrY.fa.gz
    name: ref
    type: reference
    utils:
    - args:
        remoteDir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/chromosomes/
        remoteFiles:
        - chr1.fa.gz
        - chr2.fa.gz
        - chr3.fa.gz
        - chr4.fa.gz
        - chr5.fa.gz
        - chr6.fa.gz
        - chr7.fa.gz
        - chr8.fa.gz
        - chr9.fa.gz
        - chr10.fa.gz
        - chr11.fa.gz
        - chr12.fa.gz
        - chr13.fa.gz
        - chr14.fa.gz
        - chr15.fa.gz
        - chr16.fa.gz
        - chr17.fa.gz
        - chr18.fa.gz
        - chr19.fa.gz
        - chr20.fa.gz
        - chr21.fa.gz
        - chr22.fa.gz
        - chrM.fa.gz
        - chrX.fa.gz
        - chrY.fa.gz
      completed: 2023-05-25T23:24:00
      name: fetch
    version: 30
  - build_author: alexkotlar
    build_date: 2023-07-03T15:42:00
    local_files:
    - chr1.phastCons100way.wigFix.gz
    - chr2.phastCons100way.wigFix.gz
    - chr3.phastCons100way.wigFix.gz
    - chr4.phastCons100way.wigFix.gz
    - chr5.phastCons100way.wigFix.gz
    - chr6.phastCons100way.wigFix.gz
    - chr7.phastCons100way.wigFix.gz
    - chr8.phastCons100way.wigFix.gz
    - chr9.phastCons100way.wigFix.gz
    - chr10.phastCons100way.wigFix.gz
    - chr11.phastCons100way.wigFix.gz
    - chr12.phastCons100way.wigFix.gz
    - chr13.phastCons100way.wigFix.gz
    - chr14.phastCons100way.wigFix.gz
    - chr15.phastCons100way.wigFix.gz
    - chr16.phastCons100way.wigFix.gz
    - chr17.phastCons100way.wigFix.gz
    - chr18.phastCons100way.wigFix.gz
    - chr19.phastCons100way.wigFix.gz
    - chr20.phastCons100way.wigFix.gz
    - chr21.phastCons100way.wigFix.gz
    - chr22.phastCons100way.wigFix.gz
    - chrX.phastCons100way.wigFix.gz
    - chrY.phastCons100way.wigFix.gz
    - chrM.phastCons100way.wigFix.gz
    name: phastCons
    type: score
    utils:
    - args:
        remoteDir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phastCons100way/hg19.100way.phastCons/
        remoteFiles:
        - chr1.phastCons100way.wigFix.gz
        - chr2.phastCons100way.wigFix.gz
        - chr3.phastCons100way.wigFix.gz
        - chr4.phastCons100way.wigFix.gz
        - chr5.phastCons100way.wigFix.gz
        - chr6.phastCons100way.wigFix.gz
        - chr7.phastCons100way.wigFix.gz
        - chr8.phastCons100way.wigFix.gz
        - chr9.phastCons100way.wigFix.gz
        - chr10.phastCons100way.wigFix.gz
        - chr11.phastCons100way.wigFix.gz
        - chr12.phastCons100way.wigFix.gz
        - chr13.phastCons100way.wigFix.gz
        - chr14.phastCons100way.wigFix.gz
        - chr15.phastCons100way.wigFix.gz
        - chr16.phastCons100way.wigFix.gz
        - chr17.phastCons100way.wigFix.gz
        - chr18.phastCons100way.wigFix.gz
        - chr19.phastCons100way.wigFix.gz
        - chr20.phastCons100way.wigFix.gz
        - chr21.phastCons100way.wigFix.gz
        - chr22.phastCons100way.wigFix.gz
        - chrX.phastCons100way.wigFix.gz
        - chrY.phastCons100way.wigFix.gz
        - chrM.phastCons100way.wigFix.gz
      completed: 2023-05-25T23:25:00
      name: fetch
    version: 22
  - build_author: alexkotlar
    build_date: 2023-07-03T15:42:00
    local_files:
    - chr1.phyloP100way.wigFix.gz
    - chr2.phyloP100way.wigFix.gz
    - chr3.phyloP100way.wigFix.gz
    - chr4.phyloP100way.wigFix.gz
    - chr5.phyloP100way.wigFix.gz
    - chr6.phyloP100way.wigFix.gz
    - chr7.phyloP100way.wigFix.gz
    - chr8.phyloP100way.wigFix.gz
    - chr9.phyloP100way.wigFix.gz
    - chr10.phyloP100way.wigFix.gz
    - chr11.phyloP100way.wigFix.gz
    - chr12.phyloP100way.wigFix.gz
    - chr13.phyloP100way.wigFix.gz
    - chr14.phyloP100way.wigFix.gz
    - chr15.phyloP100way.wigFix.gz
    - chr16.phyloP100way.wigFix.gz
    - chr17.phyloP100way.wigFix.gz
    - chr18.phyloP100way.wigFix.gz
    - chr19.phyloP100way.wigFix.gz
    - chr20.phyloP100way.wigFix.gz
    - chr21.phyloP100way.wigFix.gz
    - chr22.phyloP100way.wigFix.gz
    - chrX.phyloP100way.wigFix.gz
    - chrY.phyloP100way.wigFix.gz
    - chrM.phyloP100way.wigFix.gz
    name: phyloP
    type: score
    utils:
    - args:
        remoteDir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phyloP100way/hg19.100way.phyloP100way/
        remoteFiles:
        - chr1.phyloP100way.wigFix.gz
        - chr2.phyloP100way.wigFix.gz
        - chr3.phyloP100way.wigFix.gz
        - chr4.phyloP100way.wigFix.gz
        - chr5.phyloP100way.wigFix.gz
        - chr6.phyloP100way.wigFix.gz
        - chr7.phyloP100way.wigFix.gz
        - chr8.phyloP100way.wigFix.gz
        - chr9.phyloP100way.wigFix.gz
        - chr10.phyloP100way.wigFix.gz
        - chr11.phyloP100way.wigFix.gz
        - chr12.phyloP100way.wigFix.gz
        - chr13.phyloP100way.wigFix.gz
        - chr14.phyloP100way.wigFix.gz
        - chr15.phyloP100way.wigFix.gz
        - chr16.phyloP100way.wigFix.gz
        - chr17.phyloP100way.wigFix.gz
        - chr18.phyloP100way.wigFix.gz
        - chr19.phyloP100way.wigFix.gz
        - chr20.phyloP100way.wigFix.gz
        - chr21.phyloP100way.wigFix.gz
        - chr22.phyloP100way.wigFix.gz
        - chrX.phyloP100way.wigFix.gz
        - chrY.phyloP100way.wigFix.gz
        - chrM.phyloP100way.wigFix.gz
      completed: 2023-05-25T23:26:00
      name: fetch
    version: 21
  - build_author: alexkotlar
    build_date: 2023-07-03T15:42:00
    build_field_transformations:
      description: split [;]
      ensemblID: split [;]
      kgID: split [;]
      mRNA: split [;]
      protAcc: split [;]
      rfamAcc: split [;]
      spDisplayID: split [;]
      spID: split [;]
      tRnaName: split [;]
    features:
    - name
    - name2
    - description
    - kgID
    - mRNA
    - spID
    - spDisplayID
    - protAcc
    - rfamAcc
    - tRnaName
    - ensemblID
    join:
      features:
      - alleleID
      - phenotypeList
      - clinicalSignificance
      - type
      - origin
      - numberSubmitters
      - reviewStatus
      - chromStart
      - chromEnd
      track: clinvar
    local_files:
    - hg19.kgXref.chr1.gz
    - hg19.kgXref.chr2.gz
    - hg19.kgXref.chr3.gz
    - hg19.kgXref.chr4.gz
    - hg19.kgXref.chr5.gz
    - hg19.kgXref.chr6.gz
    - hg19.kgXref.chr7.gz
    - hg19.kgXref.chr8.gz
    - hg19.kgXref.chr9.gz
    - hg19.kgXref.chr10.gz
    - hg19.kgXref.chr11.gz
    - hg19.kgXref.chr12.gz
    - hg19.kgXref.chr13.gz
    - hg19.kgXref.chr14.gz
    - hg19.kgXref.chr15.gz
    - hg19.kgXref.chr16.gz
    - hg19.kgXref.chr17.gz
    - hg19.kgXref.chr18.gz
    - hg19.kgXref.chr19.gz
    - hg19.kgXref.chr20.gz
    - hg19.kgXref.chr21.gz
    - hg19.kgXref.chr22.gz
    - hg19.kgXref.chrM.gz
    - hg19.kgXref.chrX.gz
    - hg19.kgXref.chrY.gz
    name: refSeq
    type: gene
    utils:
    - args:
        connection:
          database: hg19
        sql: SELECT r.*, (SELECT GROUP_CONCAT(DISTINCT(NULLIF(x.kgID, '')) SEPARATOR
          ';') FROM kgXref x WHERE x.refseq=r.name) AS kgID, (SELECT GROUP_CONCAT(DISTINCT(NULLIF(x.description,
          '')) SEPARATOR ';') FROM kgXref x WHERE x.refseq=r.name) AS description,
          (SELECT GROUP_CONCAT(DISTINCT(NULLIF(e.value, '')) SEPARATOR ';') FROM knownToEnsembl
          e JOIN kgXref x ON x.kgID = e.name WHERE x.refseq = r.name) AS ensemblID,
          (SELECT GROUP_CONCAT(DISTINCT(NULLIF(x.tRnaName, '')) SEPARATOR ';') FROM
          kgXref x WHERE x.refseq=r.name) AS tRnaName, (SELECT GROUP_CONCAT(DISTINCT(NULLIF(x.spID,
          '')) SEPARATOR ';') FROM kgXref x WHERE x.refseq=r.name) AS spID, (SELECT
          GROUP_CONCAT(DISTINCT(NULLIF(x.spDisplayID, '')) SEPARATOR ';') FROM kgXref
          x WHERE x.refseq=r.name) AS spDisplayID, (SELECT GROUP_CONCAT(DISTINCT(NULLIF(x.protAcc,
          '')) SEPARATOR ';') FROM kgXref x WHERE x.refseq=r.name) AS protAcc, (SELECT
          GROUP_CONCAT(DISTINCT(NULLIF(x.mRNA, '')) SEPARATOR ';') FROM kgXref x WHERE
          x.refseq=r.name) AS mRNA, (SELECT GROUP_CONCAT(DISTINCT(NULLIF(x.rfamAcc,
          '')) SEPARATOR ';') FROM kgXref x WHERE x.refseq=r.name) AS rfamAcc FROM
          refGene r WHERE chrom=%chromosomes%;
      completed: 2023-05-25T23:28:00
      name: fetch
    version: 30
  - build_author: alexkotlar
    build_date: 2023-07-03T15:42:00
    build_row_filters:
      AS_FilterStatus: == PASS
    features:
    - alt
    - id
    - af: number
    - an: number
    - an_afr: number
    - an_amr: number
    - an_asj: number
    - an_eas: number
    - an_fin: number
    - an_nfe: number
    - an_oth: number
    - an_sas: number
    - an_male: number
    - an_female: number
    - af_afr: number
    - af_amr: number
    - af_asj: number
    - af_eas: number
    - af_fin: number
    - af_nfe: number
    - af_oth: number
    - af_sas: number
    - af_male: number
    - af_female: number
    fieldMap:
      AF: af
      AF_AFR: af_afr
      AF_AMR: af_amr
      AF_ASJ: af_asj
      AF_EAS: af_eas
      AF_FIN: af_fin
      AF_Female: af_female
      AF_Male: af_male
      AF_NFE: af_nfe
      AF_OTH: af_oth
      AF_SAS: af_sas
      AN: an
      AN_AFR: an_afr
      AN_AMR: an_amr
      AN_ASJ: an_asj
      AN_EAS: an_eas
      AN_FIN: an_fin
      AN_Female: an_female
      AN_Male: an_male
      AN_NFE: an_nfe
      AN_OTH: an_oth
      AN_SAS: an_sas
    local_files:
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.1.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.2.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.3.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.4.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.5.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.6.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.7.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.8.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.9.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.10.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.11.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.12.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.13.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.14.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.15.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.16.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.17.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.18.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.19.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.20.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.21.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.22.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.X.vcf.bgz
    - /mnt/files1/bystro_annotator/raw_files/hg19/gnomad2/vcf/exomes/gnomad.exomes.r2.1.1.sites.Y.vcf.bgz
    name: gnomad.exomes
    type: vcf
    version: 25
  - based: 1
    build_author: alexkotlar
    build_date: 2023-07-03T15:42:00
    build_field_transformations:
      chrom: chr .
      clinicalSignificance: split [;]
      origin: split [;]
      phenotypeList: split [;]
      reviewStatus: split [;]
      type: split [;]
    build_row_filters:
      Assembly: == GRCh38
    features:
    - alleleID: number
    - phenotypeList
    - clinicalSignificance
    - type
    - origin
    - numberSubmitters: number
    - reviewStatus
    - referenceAllele
    - alternateAllele
    fieldMap:
      '#AlleleID': alleleID
      AlternateAllele: alternateAllele
      Chromosome: chrom
      ClinicalSignificance: clinicalSignificance
      NumberSubmitters: numberSubmitters
      Origin: origin
      PhenotypeIDS: phenotypeIDs
      PhenotypeList: phenotypeList
      ReferenceAllele: referenceAllele
      ReviewStatus: reviewStatus
      Start: chromStart
      Stop: chromEnd
      Type: type
    local_files:
    - variant_summary.txt.gz
    name: clinvar
    type: sparse
    utils:
    - args:
        remoteFiles:
        - ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz
      completed: 2023-05-25T23:28:00
      name: fetch
    version: 22
version: 218

